language: ruby
rvm:
    - 2.0.0

script: xvfb-run bundle exec rake
#env:
#      - QMAKE=/usr/bin/qmake
#      - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
#before_install:
#      - sudo apt-add-repository -y ppa:canonical-qt5-edgers/qt5-proper
#      - sudo apt-get update
#      - sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev qtlocation5-dev qtsensors5-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev qt4-default
#install: bundle
